#!/usr/bin/env python3
"""
extract_js8_constants.py — generate js8_constants.{h,c} for ft8_lib from the
JS8Call (GPL-3) Fortran sources.

Source of truth (JS8Call tree):
    lib/ft8/ldpc_174_87_params.f90   generator matrix g(87), colorder(174)
    lib/ft8/bpdecode174.f90          Mn(3,174), Nm(7,87), nrw(87)
    lib/js8/genjs8.f90               Costas arrays, tone mapping, CRC-12 seed
    lib/js8/js8{a,b,c,e,i}_params.f90 submode parameters

Emitted tables follow ft8_lib's existing conventions exactly:
    - Nm / Mn hold 1-BASED indices (ldpc.c subtracts 1 at use)
    - generator rows are bit-packed MSB-first, K rounded up to whole bytes

Usage: extract_js8_constants.py <js8call-src-root> <out-dir>
"""
import re, sys, os

def read(p):
    with open(p, 'r', errors='replace') as f:
        return f.read()

def data_block(text, name):
    """Return the raw text of a Fortran `data NAME/ ... /` block."""
    m = re.search(r'data\s+' + name + r'\s*/', text)
    if not m:
        raise SystemExit('no data block for %s' % name)
    start = m.end()
    end = text.index('/', start)
    return text[start:end]

def ints(text, name):
    body = data_block(text, name).replace('&', ' ')
    return [int(t) for t in re.findall(r'-?\d+', body)]

def hexrows(text, name):
    body = data_block(text, name)
    return re.findall(r'"([0-9a-fA-F]+)"', body)

# ── parse ────────────────────────────────────────────────────────────────────
src, out = sys.argv[1], sys.argv[2]
ldpc_params = read(os.path.join(src, 'lib/ft8/ldpc_174_87_params.f90'))
bp          = read(os.path.join(src, 'lib/ft8/bpdecode174.f90'))

N, K = 174, 87
M    = N - K

g        = hexrows(ldpc_params, 'g')
colorder = ints(ldpc_params, 'colorder')
Mn_flat  = ints(bp, 'Mn')
Nm_flat  = ints(bp, 'Nm')
nrw      = ints(bp, 'nrw')

assert len(g) == M,            'generator rows: %d' % len(g)
assert len(colorder) == N,     'colorder: %d' % len(colorder)
assert len(Mn_flat) == 3 * N,  'Mn: %d' % len(Mn_flat)
assert len(Nm_flat) == 7 * M,  'Nm: %d' % len(Nm_flat)
assert len(nrw) == M,          'nrw: %d' % len(nrw)

# Fortran stores Mn(3,N) and Nm(7,M) column-major, so the flat data list is
# already row-per-bit / row-per-check in the order we want.
Mn = [Mn_flat[i*3:(i+1)*3] for i in range(N)]
Nm = [Nm_flat[i*7:(i+1)*7] for i in range(M)]

# Each generator row is 22 hex chars = 88 bits; only the first K=87 are used.
K_BYTES = (K + 7) // 8          # 11
gen = []
for row in g:
    assert len(row) == 22, row
    b = bytes.fromhex(row)
    assert len(b) == 11
    # bit 87 (the last of the 88) must be padding
    assert (b[10] & 0x01) == 0, 'generator row has a set pad bit: %s' % row
    gen.append(b)

# Cross-check nrw against the zero padding in Nm.
for m in range(M):
    nz = sum(1 for v in Nm[m] if v != 0)
    assert nz == nrw[m], 'nrw[%d]=%d but Nm row has %d entries' % (m, nrw[m], nz)

# ── submodes ────────────────────────────────────────────────────────────────
#
# NB: NTXDUR (the Fortran params) is how long a station TRANSMITS; JS8x_TX_SECONDS
# (commons.h) is the T/R CYCLE. They differ for Slow -- 28 s of transmission in a
# 30 s cycle -- and it is the cycle that slot scheduling must align to. Both are
# carried; both are asserted against upstream.
#
# (name, letter, NSUBMODE, NCOSTAS, NSPS, NTXDUR, ASTART, PERIOD)
SUBMODES = [
    ('Normal', 'A', 0, 1, 1920, 15, 0.5, 15),
    ('Fast',   'B', 1, 2, 1200, 10, 0.2, 10),
    ('Turbo',  'C', 2, 2,  600,  6, 0.1,  6),
    ('Slow',   'E', 4, 2, 3840, 28, 0.5, 30),
    ('Ultra',  'I', 8, 2,  384,  4, 0.1,  4),
]
commons = read(os.path.join(src, 'commons.h'))
# Verify each against its params file rather than trusting the table above.
for name, letter, nsub, ncos, nsps, ntx, astart, period in SUBMODES:
    p = read(os.path.join(src, 'lib/js8/js8%s_params.f90' % letter.lower()))
    def par(k):
        m = re.search(r'\b' + k + r'\s*=\s*([0-9.]+)', p)
        return m.group(1)
    assert int(par('NSUBMODE')) == nsub,  name
    assert int(par('NCOSTAS'))  == ncos,  name
    assert int(par('NSPS'))     == nsps,  name
    assert int(par('NTXDUR'))   == ntx,   name
    assert float(par('ASTART')) == astart, name
    m = re.search(r'#define\s+JS8%s_TX_SECONDS\s+(\d+)' % letter, commons)
    assert m and int(m.group(1)) == period, '%s cycle period' % name

def cbytes(b, per=11):
    return ', '.join('0x%02X' % x for x in b)

# ── emit header ─────────────────────────────────────────────────────────────
H = '''// js8_constants.h — JS8 protocol constants for ft8_lib
//
// GENERATED by extract_js8_constants.py from the JS8Call sources. Do not edit
// by hand; re-run the generator instead.
//
// Derived from JS8Call (https://github.com/js8call/js8call), GPL-3.0.
// PhantomSDR-Plus is GPL-3.0, so this is license-compatible.
//
// JS8 is FT8 *v1*: LDPC(174,87) + CRC-12, 87 information bits (75 payload +
// 12 CRC), 58 data symbols, three 7-symbol Costas blocks, 79 symbols total.
// Differences from the FT8 v2 code already in this library:
//
//   - K is 87, not 91; the CRC is 12 bits, not 14
//   - there is NO Gray mapping: three codeword bits map straight to a tone
//     (genjs8.f90: indx = cw[i]*4 + cw[i+1]*2 + cw[i+2])
//   - the codeword is [parity(87) | message(87)] and is then permuted by
//     kJS8_LDPC_colorder; FT8 v2 is [message | parity] with no permutation
//   - the CRC-12 result is XORed with 42 (genjs8.f90) before transmission
//   - submode A uses one repeated Costas array; B/C/E/I use three distinct ones
//
// Frame layout (genjs8.f90): S7 D29 S7 D29 S7
//   symbols  0..6   Costas A
//   symbols  7..35  data (29)
//   symbols 36..42  Costas B
//   symbols 43..71  data (29)
//   symbols 72..78  Costas C

#ifndef _INCLUDE_JS8_CONSTANTS_H_
#define _INCLUDE_JS8_CONSTANTS_H_

#include <stdint.h>

#define JS8_ND 58  ///< Data symbols
#define JS8_NS 21  ///< Sync symbols (3 blocks of 7)
#define JS8_NN 79  ///< Total channel symbols

#define JS8_LDPC_N       174
#define JS8_LDPC_K       87   ///< 75 payload bits + 12 CRC bits
#define JS8_LDPC_M       87   ///< N - K
#define JS8_LDPC_K_BYTES 11
#define JS8_LDPC_N_BYTES 22

#define JS8_PAYLOAD_BITS 75
#define JS8_CRC_BITS     12
#define JS8_CRC_POLY     0xC06  ///< augmented (zero-extended) CRC-12
#define JS8_CRC_XOR      42     ///< JS8-specific whitening of the CRC

/// Sync patterns. [0] = NCOSTAS 1 (submode A), [1] = NCOSTAS 2 (B/C/E/I).
/// Second index selects the beginning / middle / end block.
extern const uint8_t kJS8_Costas_pattern[2][3][7];

/// Parity generator, M rows of K bits packed MSB-first.
extern const uint8_t kJS8_LDPC_generator[JS8_LDPC_M][JS8_LDPC_K_BYTES];

/// Column permutation applied after encoding (0-based, as in the Fortran).
extern const uint8_t kJS8_LDPC_colorder[JS8_LDPC_N];

/// Checks that include each bit (1-BASED, as ft8_lib's ldpc.c expects).
extern const uint8_t kJS8_LDPC_Mn[JS8_LDPC_N][3];

/// Bits included in each check (1-BASED, zero-padded to 7).
extern const uint8_t kJS8_LDPC_Nm[JS8_LDPC_M][7];

/// Number of valid entries in each kJS8_LDPC_Nm row (5, 6 or 7).
extern const uint8_t kJS8_LDPC_Num_rows[JS8_LDPC_M];

typedef struct
{
    const char* name;      ///< "Normal", "Fast", ...
    char        letter;    ///< JS8Call submode letter (A/B/C/E/I)
    uint8_t     nsubmode;  ///< NSUBMODE, as sent on the wire / in the UI
    uint8_t     ncostas;   ///< 1 = single Costas array, 2 = three distinct
    uint16_t    nsps;      ///< Samples per symbol at 12000 Hz
    uint8_t     ntxdur;    ///< Seconds of transmission (Fortran NTXDUR)
    uint8_t     period;    ///< T/R CYCLE in seconds; differs from ntxdur for Slow
    float       baud;      ///< 12000 / nsps; also the tone spacing in Hz
    float       bandwidth; ///< 8 * baud
    float       frame_dur; ///< 79 * nsps / 12000, seconds
    float       start_delay; ///< ASTART: capture lead-in, seconds
} js8_submode_t;

#define JS8_NUM_SUBMODES %d
extern const js8_submode_t kJS8_submodes[JS8_NUM_SUBMODES];

#endif // _INCLUDE_JS8_CONSTANTS_H_
''' % len(SUBMODES)

# ── emit source ─────────────────────────────────────────────────────────────
lines = []
lines.append('// js8_constants.c — GENERATED by extract_js8_constants.py. Do not edit.')
lines.append('// Derived from JS8Call (GPL-3.0): lib/ft8/ldpc_174_87_params.f90,')
lines.append('// lib/ft8/bpdecode174.f90, lib/js8/genjs8.f90, lib/js8/js8*_params.f90')
lines.append('')
lines.append('#include "js8_constants.h"')
lines.append('')
lines.append('const uint8_t kJS8_Costas_pattern[2][3][7] = {')
lines.append('    // NCOSTAS 1 — submode A (Normal): one pattern repeated')
lines.append('    { { 4, 2, 5, 6, 1, 3, 0 }, { 4, 2, 5, 6, 1, 3, 0 }, { 4, 2, 5, 6, 1, 3, 0 } },')
lines.append('    // NCOSTAS 2 — submodes B/C/E/I: three distinct patterns')
lines.append('    { { 0, 6, 2, 3, 5, 4, 1 }, { 1, 5, 0, 2, 3, 6, 4 }, { 2, 5, 0, 6, 4, 1, 3 } },')
lines.append('};')
lines.append('')

lines.append('const uint8_t kJS8_LDPC_generator[JS8_LDPC_M][JS8_LDPC_K_BYTES] = {')
for row in gen:
    lines.append('    { %s },' % cbytes(row))
lines.append('};')
lines.append('')

lines.append('const uint8_t kJS8_LDPC_colorder[JS8_LDPC_N] = {')
for i in range(0, N, 20):
    lines.append('    ' + ', '.join('%3d' % v for v in colorder[i:i+20]) + ',')
lines.append('};')
lines.append('')

lines.append('const uint8_t kJS8_LDPC_Mn[JS8_LDPC_N][3] = {')
for r in Mn:
    lines.append('    { %s },' % ', '.join('%3d' % v for v in r))
lines.append('};')
lines.append('')

lines.append('const uint8_t kJS8_LDPC_Nm[JS8_LDPC_M][7] = {')
for r in Nm:
    lines.append('    { %s },' % ', '.join('%3d' % v for v in r))
lines.append('};')
lines.append('')

lines.append('const uint8_t kJS8_LDPC_Num_rows[JS8_LDPC_M] = {')
for i in range(0, M, 20):
    lines.append('    ' + ', '.join('%d' % v for v in nrw[i:i+20]) + ',')
lines.append('};')
lines.append('')

lines.append('const js8_submode_t kJS8_submodes[JS8_NUM_SUBMODES] = {')
for name, letter, nsub, ncos, nsps, ntx, astart, period in SUBMODES:
    baud = 12000.0 / nsps
    lines.append('    { "%s", \'%s\', %d, %d, %d, %d, %d, %.6ff, %.6ff, %.6ff, %.3ff },'
                 % (name, letter, nsub, ncos, nsps, ntx, period,
                    baud, 8 * baud, 79.0 * nsps / 12000.0, astart))
lines.append('};')
lines.append('')

os.makedirs(out, exist_ok=True)
open(os.path.join(out, 'js8_constants.h'), 'w').write(H)
open(os.path.join(out, 'js8_constants.c'), 'w').write('\n'.join(lines))

print('generator rows : %d x %d bits' % (len(gen), K))
print('colorder       : %d entries, %d unique' % (len(colorder), len(set(colorder))))
print('Mn             : %d x 3' % len(Mn))
print('Nm             : %d x 7 (row weights %s)' % (len(Nm), sorted(set(nrw))))
print('submodes       : %s' % ', '.join('%s(%ds tx/%ds cycle)' % (s[0], s[5], s[7]) for s in SUBMODES))
print('wrote %s/js8_constants.{h,c}' % out)
