// js8_constants.h — JS8 protocol constants for ft8_lib
//
// GENERATED by extract_js8_constants.py from the JS8Call sources. Do not edit
// by hand; re-run the generator instead.
//
// Derived from JS8Call (https://github.com/js8call/js8call), GPL-3.0.
// PhantomSDR-Plus is GPL-3.0, so this is license-compatible.
//
// JS8 is FT8 *v1*: LDPC(174,87) + CRC-12, 87 information bits (75 payload +
// 12 CRC), 58 data symbols, three 7-symbol Costas blocks, 79 symbols total.
// Differences from the FT8 v2 code already in this library:
//
//   - K is 87, not 91; the CRC is 12 bits, not 14
//   - there is NO Gray mapping: three codeword bits map straight to a tone
//     (genjs8.f90: indx = cw[i]*4 + cw[i+1]*2 + cw[i+2])
//   - the codeword is [parity(87) | message(87)] and is then permuted by
//     kJS8_LDPC_colorder; FT8 v2 is [message | parity] with no permutation
//   - the CRC-12 result is XORed with 42 (genjs8.f90) before transmission
//   - submode A uses one repeated Costas array; B/C/E/I use three distinct ones
//
// Frame layout (genjs8.f90): S7 D29 S7 D29 S7
//   symbols  0..6   Costas A
//   symbols  7..35  data (29)
//   symbols 36..42  Costas B
//   symbols 43..71  data (29)
//   symbols 72..78  Costas C

#ifndef _INCLUDE_JS8_CONSTANTS_H_
#define _INCLUDE_JS8_CONSTANTS_H_

#include <stdint.h>

#define JS8_ND 58  ///< Data symbols
#define JS8_NS 21  ///< Sync symbols (3 blocks of 7)
#define JS8_NN 79  ///< Total channel symbols

#define JS8_LDPC_N       174
#define JS8_LDPC_K       87   ///< 75 payload bits + 12 CRC bits
#define JS8_LDPC_M       87   ///< N - K
#define JS8_LDPC_K_BYTES 11
#define JS8_LDPC_N_BYTES 22

#define JS8_PAYLOAD_BITS 75
#define JS8_CRC_BITS     12
#define JS8_CRC_POLY     0xC06  ///< augmented (zero-extended) CRC-12
#define JS8_CRC_XOR      42     ///< JS8-specific whitening of the CRC

/// Sync patterns. [0] = NCOSTAS 1 (submode A), [1] = NCOSTAS 2 (B/C/E/I).
/// Second index selects the beginning / middle / end block.
extern const uint8_t kJS8_Costas_pattern[2][3][7];

/// Parity generator, M rows of K bits packed MSB-first.
extern const uint8_t kJS8_LDPC_generator[JS8_LDPC_M][JS8_LDPC_K_BYTES];

/// Column permutation applied after encoding (0-based, as in the Fortran).
extern const uint8_t kJS8_LDPC_colorder[JS8_LDPC_N];

/// Checks that include each bit (1-BASED, as ft8_lib's ldpc.c expects).
extern const uint8_t kJS8_LDPC_Mn[JS8_LDPC_N][3];

/// Bits included in each check (1-BASED, zero-padded to 7).
extern const uint8_t kJS8_LDPC_Nm[JS8_LDPC_M][7];

/// Number of valid entries in each kJS8_LDPC_Nm row (5, 6 or 7).
extern const uint8_t kJS8_LDPC_Num_rows[JS8_LDPC_M];

typedef struct
{
    const char* name;      ///< "Normal", "Fast", ...
    char        letter;    ///< JS8Call submode letter (A/B/C/E/I)
    uint8_t     nsubmode;  ///< NSUBMODE, as sent on the wire / in the UI
    uint8_t     ncostas;   ///< 1 = single Costas array, 2 = three distinct
    uint16_t    nsps;      ///< Samples per symbol at 12000 Hz
    uint8_t     ntxdur;    ///< Seconds of transmission (Fortran NTXDUR)
    uint8_t     period;    ///< T/R CYCLE in seconds; differs from ntxdur for Slow
    float       baud;      ///< 12000 / nsps; also the tone spacing in Hz
    float       bandwidth; ///< 8 * baud
    float       frame_dur; ///< 79 * nsps / 12000, seconds
    float       start_delay; ///< ASTART: capture lead-in, seconds
} js8_submode_t;

#define JS8_NUM_SUBMODES 5
extern const js8_submode_t kJS8_submodes[JS8_NUM_SUBMODES];

#endif // _INCLUDE_JS8_CONSTANTS_H_
